name: Weekly Meta Update

on:
  schedule:
    - cron: '0 */12 * * *' # This line schedules the workflow to run every 12 hours

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.push_token }}

      - name: Download meta.json
        run: |
          wget -O meta.new https://api.github.com/meta
          # format the json file with line breaks
          jq . meta.new > meta.json



      - name: Push changes
        run: |
          git diff --quiet && git diff --staged --quiet || (git config --local user.email "action@github.com" && git config --local user.name "GitHub Action" && git add . && git commit -m "Add changes" && git push)