name: Weekly Meta Update

on:
  schedule:
    - cron: '0 0 * * 0' # This line schedules the workflow to run every Sunday at 00:00

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download meta.json
        run: wget -O meta.new https://api.github.com/meta

      - name: Push changes
            run: |
              cp meta.new meta.json
              # TODO: Add a check to see if the file has changed
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add .
              git commit -m "Add changes"
              git push